---

- name: logrotate > Template base
  template:
    src:   logrotate/base.j2
    dest:  "{{ elao_php_logrotate_file }}"
    owner: root
    group: root
    mode:  0644
  when: (elao_php_logrotate_template is none) and (not elao_php_logrotate_config|length)

- name: logrotate > Template
  template:
    src:   "{{ elao_php_logrotate_template|ternary(elao_php_logrotate_template, 'logrotate/empty.j2') }}"
    dest:  "{{ elao_php_logrotate_file }}"
    owner: root
    group: root
    mode:  0644
  when: (elao_php_logrotate_template is not none) or (elao_php_logrotate_config|length)
