---

- name: logs > Directory
  file:
    path:  "{{  elao_php_log_dir }}"
    state: directory
    owner: root
    group: root
    mode:  0755

- name: logs > File touch
  command: "touch {{ elao_php_log_dir }}/error.log"
  args:
    creates: "{{ elao_php_log_dir }}/error.log"

- name: logs > File
  file:
    path:  "{{ elao_php_log_dir }}/error.log"
    owner: "{{ elao_php_user }}"
    mode:  0640
