---

# Tasks
elao_mysql_tasks_include: ~
elao_mysql_tasks_exlude: []

# Configs
elao_mysql_configs_exclusive: false
elao_mysql_configs_dir:       /etc/mysql/conf.d
elao_mysql_configs_template:  configs/empty.cnf.j2
elao_mysql_configs:           []

# Mysql users
elao_mysql_users: []

# Mysql databases
elao_mysql_databases: []
