---

- name: packages > Manage packages
  apt:
    name:  "{{ item.name }}"
    force: "{{ item.force|default(omit) }}"
    state: "{{ item.state|default('present') }}"
  with_items: elao_apt_packages
