---

- name: repositories > Keys
  apt_key:
    url:   "{{ item.key.url }}"
    id:    "{{ item.key.id }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ elao_apt_repositories|select('mapping')|list }}"
  when: item.key is defined

- name: repositories > Sources
  apt_repository:
    repo:         "{{ item.source }}"
    state:        "{{ item.state|default('present') }}"
    update_cache: yes
  with_items: "{{ elao_apt_repositories|select('mapping')|list }}"

- name: repositories > Patterns keys
  apt_key:
    url:   "{{ elao_apt_repositories_patterns[item.split('/')[0]].key.url }}"
    id:    "{{ elao_apt_repositories_patterns[item.split('/')[0]].key.id }}"
    state: "{{ item.split('/')[1]|default('present') }}"
  with_items: "{{ elao_apt_repositories|select('string')|list }}"
  when: elao_apt_repositories_patterns[item.split('/')[0]].key is defined

- name: repositories > Patterns sources
  apt_repository:
    repo:         "{{ elao_apt_repositories_patterns[item.split('/')[0]].source }}"
    state:        "{{ item.split('/')[1]|default('present') }}"
    update_cache: yes
  with_items: "{{ elao_apt_repositories|select('string')|list }}"
