---

- name: template > Template
  template:
    src:  "{{ elao_motd_template|ternary(elao_motd_template, 'template/empty.j2') }}"
    dest: "{{ elao_motd_file }}"
  when: (elao_motd_template is not none) or (elao_motd is not none)
