---

- name: config > Template
  template:
    src:  "{{ elao_git_config_template|ternary(elao_git_config_template, 'config/empty.j2') }}"
    dest: "{{ elao_git_config_file }}"
  when: (elao_git_config_template is not none) or (elao_git_config|length)
