---

- name: repositories > Setup git repositories
  git:
    repo:           "{{ item.repo }}"
    dest:           "{{ item.dest }}"
    accept_hostkey: "{{ item.accept_hostkey|default(omit) }}"
    clone:          "{{ item.clone|default(omit) }}"
    update:         "{{ item.update|default(true)|bool }}"
  with_items: elao_git_repositories
