---

dependencies: []

galaxy_info:

  author:              ELAO
  company:             ELAO
  description:         An apt role for elao symfony standard vagrant box
  license:             MIT
  min_ansible_version: 1.7.2
  platforms:
    - name: Debian
      versions:
        - wheezy
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - development
    - web
