---

- name: config > Template
  template:
    src:  "{{ elao_nginx_config_template|ternary(elao_nginx_config_template, 'config/http_base.conf.j2') }}"
    dest: "{{ elao_nginx_config_file }}"
  when: (elao_nginx_config_template is not none) or (elao_nginx_config|length)
  notify:
    - nginx restart
