---

- name: logs > Files
  file:
    path:  "{{ item }}"
    owner: "{{ elao_nginx_user }}"
    group: adm
    mode:  0640
  with_items:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
